apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassistant
spec:
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - image: ghcr.io/home-assistant/home-assistant:stable
          imagePullPolicy: Always
          name: homeassistant
          env:
            - name: TZ
              value: "Europe/Vienna"
          securityContext:
            privileged: true
          ports:
            - containerPort: 8123
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: '/config/configuration.yaml'
              subPath: 'configuration.yaml'
            - name: localtime
              mountPath: '/etc/localtime'
              readOnly: true
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 2Gi
              cpu: 1
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: config-volume
          configMap:
            name: hoa-cfgmap
      restartPolicy: Always