apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homeassistant
            port:
              number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
spec:
  ports:
    - port: 8123
      protocol: TCP
  selector:
    app:  homeassistant
